In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [2]:
soup = BeautifulSoup(requests.get('https://kworb.net/spotify/').text)

In [3]:
link_list = [l['href'] for l in soup.find('table').find_all('a', href=True) 
 if ('weekly' in l['href']) and ('totals' not in l['href'])]

In [4]:
link_list[:5]

['country/global_weekly.html',
 'country/us_weekly.html',
 'country/gb_weekly.html',
 'country/ad_weekly.html',
 'country/ar_weekly.html']

In [5]:
for link in link_list[:3]:
    display(pd.read_html(f'https://kworb.net/spotify/{link}')[0].head())

,Pos,P+,Artist and Title,Wks,Pk,(x?),Streams,Streams+,Total
0,1,=,Xavi - La Diabla,9,1,(x4),36184432,-1953880.0,280997027
1,2,=,Tate McRae - greedy,21,1,(x4),35438103,755009.0,738388826
2,3,+12,Benson Boone - Beautiful Things,3,3,(x1),34070246,10302428.0,76058079
3,4,-1,"The Weeknd - One Of The Girls (w/ JENNIE, Lily...",18,3,(x1),33826703,113218.0,372862481
4,5,+2,Taylor Swift - Cruel Summer,53,2,(x3),30425874,1236219.0,1270930479

,Pos,P+,Artist and Title,Wks,Pk,(x?),Streams,Streams+,Total
0,1,+6,Benson Boone - Beautiful Things,3,1,(x1),11372296,3093512.0,27033212
1,2,+2,Noah Kahan - Stick Season,67,2,(x3),10479567,335618.0,264877843
2,3,-2,21 Savage - redrum,4,1,(x1),9783073,-819219.0,41622220
3,4,-2,Jack Harlow - Lovin On Me,13,1,(x4),9181119,-1136490.0,136855261
4,5,=,Zach Bryan - I Remember Everything (w/ Kacey M...,24,1,(x1),8956651,-225266.0,215283106

,Pos,P+,Artist and Title,Wks,Pk,(x?),Streams,Streams+,Total
0,1,=,Noah Kahan - Stick Season,19,1,(x6),5035681,-337952.0,57637801
1,2,=,Sophie Ellis-Bextor - Murder On The Dancefloor,7,2,(x5),3075440,-701376.0,20594621
2,3,+1,Teddy Swims - Lose Control,12,3,(x1),2585522,-11470.0,15439015
3,4,-1,Jack Harlow - Lovin On Me,13,1,(x3),2377794,-409481.0,40067599
4,5,+9,Benson Boone - Beautiful Things,3,5,NaN,2241710,641840.0,4990012